#Workflow의 이름
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정하는 곳
#github에서 무언가가 발생했을 때 github actions를 실행시키고 싶다.
#어느 시점에 어떤 경우에 실행시키고 싶은지를 나타낸다.
#main이라는 branch에 push됄 때 실행시킨다.
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개이상의 Job으로 구성된다.
# 여러 Job은 기본적으로 병렬적으로 수행된다.
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # 운영체제를 고르는 곳
    # ubuntu 환경 / 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # Step: 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps:
      - name: Hello World 찍기
        # echo : 출력하는 명령어 (리눅스)
        run : echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"

      # $ 기호는 이변수 이름표를 떼고 그 안에 들어있는 실제값으로 바꿔줘라는 뜻
      # echo $GITHUB_SHA : 이 변수안에 든 값을 출력해라. 7b3f1c...(실제 커밋 해시)
      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기=
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 아무한테 노출이 되면 안되는 값
        run: |
          echo ${{ secrets.MY_NAME}}
